services:
  tmflow:
    container_name: tmflow
    image: ghcr.io/collaborativeroboticslab/omron_win_software-tmflow:latest
    pull_policy: always
    privileged: true
    network_mode: host
    environment:
      DISPLAY: ${DISPLAY}
      XAUTHORITY: /root/.Xauthority
      WINEPREFIX: /wine
      QT_X11_NO_MITSHM: "1"
    volumes:
      - /dev:/dev
      - ${HOME}/.Xauthority:/root/.Xauthority:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - tmflow-wine:/wine

volumes:
  tmflow-wine: